server:
  port: 8087
  servlet:
    context-path: '/Culinaryapi-MenuService/'

spring:
  application:
    name: Culinaryapi-MenuService
  datasource:
    url:  jdbc:postgresql://localhost:5432/Culinaryapi-MenuService
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true