spring:
  application:
    name: CulinaryApi-Menu-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: culinaryapi-config-server
      username: configserver
      password: 'culinary123cs'
